language: r
r:
  - release
dist: trusty  # ubuntu 14.04 has additional libraries available
sudo: required
cache: false
warnings_are_errors: false

env:
  global:
  - secure: NcVQvyHnASlssXLU0vuKfsnmlt9edlnOHd7tFUUGLDNtx5qikqewnIN0YCnzobFAF3BZbDT9Zql/9x0U2AIxsFZ6ArNyebrSvrOZAJ7/rkyCWjaVwGwVCHEuhgyJ2lcME1HZKChNcA4Kc4P9/qgUwn1tdQnb2xm9+0nIW2qivE4V7i5MSDSgM1uKI1sQu7sfTMVD3Dtgtc3PzaDXhfOiRR+tKLInHHlDd2OVL928yl8GBdgso0ObSKaPuT0RH7DnJkfjtrRBl/LPkyz/oIs2k71TvgkybBV9pSLmQjUK/snW9LYqXxwN6LAvujb+lCl4YmoX+Z5Y2sE/AIzuvRTMuvE4WmTMT5kmWlmGd0ryLgqV3bcUuDQnj4TmQNffBSEQkdGJK/gbsaaDvyO8OdC0E8bkcwseu8485tVxszcL5yUCFVQDaP+iI/mkkHO2h3JGUvW2MN1WUvgzGSUcnGdshVcBf2alorLU0P7uzx52va+WxYoJA003njiJYHY9IDVuVUIKo2sWTEC5UIVQ8T2YGrCUB1NTAQFheFFVkzTSO2uCAzBfyqYyc+412grPITUOntTJoH7OjSF3gb5Zoe+Rm1kn5QrUdb9+O0kGkHNIvmcg+tX6VlUSN7s9n2QNzFM77CGFnfXEYsdgTUBzmrNaTQCZihAHN2xIdF57GjH0qOI=

# install debian libraries to match R-servers
# update pre-installed packages to latest versions
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev python-protobuf libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev
  - rcode="res<-devtools::test(); "
  - rcode+="df <- as.data.frame(res); "
  - rcode+='pass <- sum(df$failed)==0 && all(!df$error); '
  - rcode+="write.csv(df, file='test_results.csv'); "
  - rcode+="quit(status=1-pass, save='no');"

r_packages:
  - roxygen2
  - covr

r_github_packages:
  - Displayr/flipDevTools
  - Displayr/flipExampleData

script:
  - R CMD build --no-manual --no-build-vignettes --no-resave-data .
  - R CMD check --as-cran --no-manual --no-build-vignettes --no-tests *.tar.gz
  - Rscript -e 'install.packages("webshot"); webshot::install_phantomjs()'
  - if [ -d tests/testthat ]; then
    Rscript --default-packages='datasets,utils,grDevices,graphics,stats,methods' -e "$rcode";
    fi
  - git config user.name travisCISnapshots
  - git remote set-url origin "https://$WTOKEN@github.com/Displayr/flipChartTests.git"
  - git add tests/testthat/snapshots/*/*.pdf
  - git commit -m "Snapshots added from Travis build $TRAVIS_BUILD_NUMBER [ci skip]"
  - git push origin master

#notifications:
#  slack:
#    rooms:
#      - displayr:FTgSTNHC2rpanhJMGTKMwZXM#github-notifications
#    template:
#      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_message}>"
#    on_success: change
#    on_failure: always

# Warning notifications and downstream package builds are implemented
# by calling R functions so they can be updated in this package without
# committing a new change to .travis.yml in each repository
#after_success:
#  - Rscript -e "require(flipDevTools); NotifyWarnings(); TriggerDownstreamBuilds()"
#  - travis_wait Rscript -e "flipDevTools::CheckCoverage()"
