version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:723066c2c797171f853da01c57cae63812c42c2e
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine]
    default: nightly
  save-snapshots:
    type: boolean
    default: true

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build-and-check-package:
          executor: << pipeline.parameters.executor >>
          resource-class: small
          name: BuildAndCheckPackage
          context:
            - rviz_packages
          remote-deps: << pipeline.parameters.remote-deps >>
          separate-test-job: true
          save-snapshots: false
      - r-packages/test-package:
          executor: << pipeline.parameters.executor >>
          resource-class: small
          name: TestPackage
          save-snapshots: << pipeline.parameters.save-snapshots >>
          requires:
            - BuildAndCheckPackage
          context:
            - rviz_packages
